### ISSUE TITLE
[win10] failed to run custom build command for `opus-sys v0.2.1

### ISSUE THREAD

**Issue by LDSpits** [SpaceManiac/opus-rs#11]
Hi there, while I was trying to build a default binary project using your package for opus i got the following error while trying to run this on windows.

```
error: failed to run custom build command for `opus-sys v0.2.1 (file:///C:/Users/Lucas/.cargo/registry/src/github.com-1ecc6299db9ec823/opus-sys-0.2.1)`
process didn't exit successfully: `C:\Users\Lucas\.cargo\registry\src\github.com-1ecc6299db9ec823\opus-sys-0.2.1\target\debug\build\opus-sys-29399958ba2f848b\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'The system cannot find the file specified. (os error 2)', build.rs:73:22
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Any idea what files might be missing?

**Comment by SpaceManiac** [comment]
Probably `sh` or `make`. Regrettably, the buildscript for `opus-sys` currently requires a UNIX-ish toolchain (I use MSYS2):

https://github.com/lgvz/rust-opus/blob/be9968c78630fb0b469f39900c3950987240c37c/opus-sys/build.rs#L24-L32

Having `opus-sys` work in an MSVC environment is a valid issue but it belongs on that repo.
