### ISSUE TITLE
Bindings lose ability to encode packet loss 

### ISSUE THREAD

**Issue by FrancisRussell** [SpaceManiac/opus-rs#17]
The C functions `opus_decode_float` and `opus_decode` take a null pointer for `data` to encode packet loss. The Rust bindings take a slice for this parameter so it does not appear to be possible to indicate this case though the Rust API.

**Comment by SpaceManiac** [comment]
If you pass an empty slice `&[]`, that will be passed along to the C library as packet loss.

**Comment by FrancisRussell** [comment]
Ah fair enough. It would be nice is the docs for the Rust wrapping functions mentioned this behaviour.
